### ISSUE TITLE
Feature request: add tileabletextures to floors

### ISSUE THREAD

**Issue by baileywick** [mcglincy/dungeondraw-foundry-vtt#1]
Sources like Forgotten Adventures have great textures that would create nice looking floors. Would be great to add them to the floor config and to set as default.

**Comment by mcglincy** [comment]
Great suggestion! I'll take a look at implementing that.

**Comment by mcglincy** [comment]
I still need to work out some of the UI and sizing (selecting a texture in the config, how to size things to match the scene grid, etc), but it looks like this should be very possible.

![Screen Shot 2021-11-09 at 2 50 05 PM](https://user-images.githubusercontent.com/189172/141003017-2961057d-bafd-4477-9d83-e052b83cb9f9.png)

**Comment by mcglincy** [comment]
Implemented in new version 0.4.0. Let me know if you hit any snags!

**Comment by baileywick** [comment]
heck yeah! looks great
