### ISSUE TITLE
Add an interior wall tool

### ISSUE THREAD

**Issue by mcglincy** [mcglincy/dungeondraw-foundry-vtt#10]

**Comment by pseudocode** [comment]
In addition to an explicit "draw a wall between those two points" tool, it might be a good idea to change how the "add rectangle" tool works. When the new selection is not overlapping with an existing room, it could place an interior wall on the intersection. If it overlaps, it would create a merged room.

This is the way DungeonScrawl handles it:

Starting with this simple 2x2 room, I want to add another 2x2 room:
![starting-room](https://user-images.githubusercontent.com/119981/141805620-12734316-2131-4919-ac83-486f5773cb73.jpg)

If my selection for this room starts in the middle of the previous one (i.e. a 3x2 selection), I'd get this
![overlapping-selection](https://user-images.githubusercontent.com/119981/141805616-59b851aa-2d87-4ce1-88c7-66e7a893a3ae.jpg)

If the new selection starts at the western end of the room, it'll end up looking like this:
![adjacent-selection](https://user-images.githubusercontent.com/119981/141805610-3c1fedb6-6b0b-44bc-a2d2-029d067f27bf.jpg)

This would be a good workflow for improvisational drawing. If the rooms remain collapsed, I'd have to add a wall manually and possible too much gets revealed while that isn't brought up.

**Comment by mcglincy** [comment]
Thanks for the detailed write up! And yeah, I agree being able to draw side by side rooms like this would be a nice improvement. 

There may be some wrinkles with how I'm currently storing the dungeon (as a single geometry) and adding new rectangles to it (as a union, solved by the jsts topology library I'm using)... but I'll take a look.

**Comment by mcglincy** [comment]
First step: implemented a simpler "draw a wall between those two points" tool in 0.8.0.

I'm still thinking about how I might handle supporting shared wall / side by side rectangle addition.

**Comment by mcglincy** [comment]
OK, now that interior walls exist in my data model, I think I've got a serviceable first implementation of adding a rectangle with a shared wall.

Now when you add a rectangle, if it only "touches" (only shares a wall, doesn't overlap) with the existing geometry, I create a new interior wall for that touching section. 

This will ship in upcoming version 0.9.0.
