### ISSUE TITLE
Support for V10 [FEATURE REQUEST]

### ISSUE THREAD

**Issue by kiloforce** [mcglincy/dungeondraw-foundry-vtt#103]
Requesting FoundryVTT V10 support.

When I load Dungeon Draw version 0.25.0 on v10.284.  I get the following errors:

![image](https://user-images.githubusercontent.com/433058/188525012-5152af7c-9995-44d7-a445-4426243ca4d5.png)

**Comment by mcglincy** [comment]
Thanks for the report. I've updated the code for v10 compatibility, and am now doing some final data migration testing before releasing it.

**Comment by mcglincy** [comment]
@kiloforce new module build to test out (and please back up your worlds directory first!): https://github.com/mcglincy/dungeondraw-foundry-vtt/releases/download/1.0.0/module.json

**Comment by githuberto** [comment]
I'm having some issues with this new build:

- Themes aren't working (just get the default white floor with black walls regardless of which I pick).
- The theme painter tool only draws a single white line and doesn't apply anything.
- The dungeon generator fails with the following:
```
Error: Unexpected `NAN` at position 9 in `POLYGON((NaN NaN, NaN[object Object] NaN, NaN[object Object] NaN[object Object], NaN NaN[object Object], NaN NaN))`
    parsePoint_ WKTParser.js:447
    parsePointList_ WKTParser.js:455
    parseLineStringText_ WKTParser.js:357
    parseLineStringTextList_ WKTParser.js:477
    parsePolygonText_ WKTParser.js:372
    parseGeometry_ WKTParser.js:565
    parse WKTParser.js:292
    read WKTParser.js:770
    read WKTReader.js:40
    Nr geo-utils.js:77
    dc generator.js:127
    generate generator.js:10
    generate dungeonlayer.js:212
    generate generatorsheet.js:79
    jQuery 9
    activateListeners generatorsheet.js:60
    _render foundry.js:4989
    _render foundry.js:5684
    render foundry.js:4918
    onClick dungeondraw.js:76
    _onClickTool foundry.js:66673
    jQuery 9
    activateListeners foundry.js:66628
    _render foundry.js:4989
    render foundry.js:4918
    initialize foundry.js:66584
    activate foundry.js:30071
    _onClickLayer foundry.js:66647
    jQuery 9
    activateListeners foundry.js:66627
    _render foundry.js:4989
    render foundry.js:4918
    initialize foundry.js:66584
[generator.js:20:12](http://127.0.0.1:34542/modules/dungeon-draw/src/generator.js)
    generate generator.js:20
    generate dungeonlayer.js:212
    generate generatorsheet.js:79
    jQuery 9
    activateListeners generatorsheet.js:60
    _render foundry.js:4989
    _render foundry.js:5684
    render foundry.js:4918
    onClick dungeondraw.js:76
    _onClickTool foundry.js:66673
    jQuery 9
    activateListeners foundry.js:66628
    _render foundry.js:4989
    render foundry.js:4918
    initialize foundry.js:66584
    activate foundry.js:30071
    _onClickLayer foundry.js:66647
    jQuery 9
    activateListeners foundry.js:66627
    _render foundry.js:4989
    render foundry.js:4918
    initialize foundry.js:66584
```

**Comment by mcglincy** [comment]
Thanks for the report. I am going to dig into and explicitly test each tool. It seems like Foundry v10 changed the structure of Drawings, which breaks Dungeon Draw in all sorts of ways.

**Comment by mcglincy** [comment]
Ok, that was a bunch of work, but I believe I now have Dungeon Draw working with v10. 

Here's the latest manifest: https://github.com/mcglincy/dungeondraw-foundry-vtt/releases/download/1.0.1/module.json

I'm aware of one still-outstanding issue with the "Save to Scene Background" tool and texture caches, which I'm tracking on #104.

@kiloforce and @githuberto , please give v1.0.1 a try and let me know if you notice any issues. Thanks!

**Comment by githuberto** [comment]
@mcglincy so sorry, I missed the notification. It's working great for me, love this module. Thanks for the speedy update!

**Comment by mcglincy** [comment]
👍 closing.
