### ISSUE TITLE
Heavy incompatibility with libWrapper

### ISSUE THREAD

**Issue by marcusadmortati** [mcglincy/dungeondraw-foundry-vtt#110]
Dungeon Draw is inoperable with libWrapper enabled.

**Comment by mcglincy** [comment]
Sorry it's taken so long to comment on this; I must have missed the notification email.

Do you have a specific error message you're seeing w/ Dungeon Draw + libWrapper?  (I'll also test it locally.)

**Comment by mcglincy** [comment]
@marcusadmortati I just tested with Foundry 10.288 with Dungeon Draw and libWrapper modules enabled, and was able to draw a map successfully with dungeon draw. Can you verify whether you're still hitting problems, and if so report back with any visible errors on the javascript console?

**Comment by PXR5** [comment]
Just for info, working fine with 11.313 with libWrapper enabled.

**Comment by mcglincy** [comment]
Thanks @PXR5 ! I'll mark this as closed, and @marcusadmortati can re-open if still having issues on latest Foundry/libwrapper.
