### ISSUE TITLE
Draw over existing walls/doors in scene

### ISSUE THREAD

**Issue by Timecrash** [mcglincy/dungeondraw-foundry-vtt#112]
I'm unsure if this is possible or already implemented, but here's my use case:

1. Using the Foundry wall controls, draw a dungeon map with walls, doors, etc.
2. Choose an 'Draw Over Existing Walls' option in the Dungeon Draw controls or something similar.
3. Dungeon Draw will take the existing wall/door data (boundaries, length, etc.) and draw over each element using its analogous element.

I had set up a pretty complex dungeon map using the Foundry wall controls, then found that I couldn't actually use any of that data with Dungeon Draw. I was copying a map set as the background image as a guide, which listed all the secrets, and I obviously can't have the players see, so I was going to delete that map, then have Dungeon Draw render a map using the existing data, but it seems this isn't possible.

I don't know if this is entirely out of scope for this module, so apologies if it is. There's a module that seemingly does what I want, [DrawnWallGenerator](https://github.com/kid2407/DrawnWallGenerator), but it hasn't been updated since Foundry V8.

**Comment by mcglincy** [comment]
As I started reading your text, I was planning to point you at DrawnWallGenerator, but you've already linked it :)

Currently Dungeon Draw's process is the inverse of what you're requesting: it lets you draw the dungeon geometry using its tools, and then it auto-generates the Foundry walls from that.

Have you pinged the DrawnWallGenerator author to see if they're going to update it for v10?

**Comment by Timecrash** [comment]
Was gonna do that after I got a response here :)

And yeah, I realize now I should have started with Dungeon Draw, which of course only came after me spending two hours doing the map with the default wall controls. I know better for next time!

I'll be closing this issue (unless you really want to add this functionality), thanks for the reply!
