### ISSUE TITLE
Option to disable creation of Foundry walls when drawing

### ISSUE THREAD

**Issue by aniki21** [mcglincy/dungeondraw-foundry-vtt#113]
I've been using Dundgeon Draw to map out rough location layouts in my games, but the automatic wall creation means that players often lose line of sight or can't move their tokens as I add new parts.

Would it be possible to add an option to not create Wall objects on the scene?

**Comment by mcglincy** [comment]
Yup, that sounds doable. Probably a module setting checkbox that defaults to enabled?

**Comment by cpcodes** [comment]
That would be awesome. I have a different use case, but would also love to be able to build without walls.

**Comment by mcglincy** [comment]
Implemented for upcoming release 2.2.0.

**Comment by cpcodes** [comment]
Any idea when 2.2.0 is expected?

**Comment by mcglincy** [comment]
So sorry - I closed this issue thinking it was complete and pushed, but it wasn't. Re-opening and will check what happened to my code change.

**Comment by mcglincy** [comment]
Merged my lost code and pushed a new version 2.3.0.

Take a look and let me know if you hit any problems!
