### ISSUE TITLE
Dungeondraw is not drawing rooms. (Error with lib-wrapper?)

### ISSUE THREAD

**Issue by Hentik** [mcglincy/dungeondraw-foundry-vtt#116]
Describe the bug
Dungeon Draw doesnt create rooms anymore and the preview ofthe room siz e doesnt show anymore as well.

To Reproduce
Try to draw on any scene. 

Expected behavior
Drawing on a scene with dungeondraw activated should create a room.

Screenshots
image
![Capturethis](https://github.com/mcglincy/dungeondraw-foundry-vtt/assets/36681809/9f24878c-fc32-4e11-aa4a-21a49a5da2e6)

Browser Chrome
Foundry Version 10.291
System DND 5e 2.2.1
module version 2.0.1

**Comment by mcglincy** [comment]
@Hentik Can you manually downgrade to the previous Dungeon Draw version, or uninstall/reinstall? 

versions 2.0.1+ only work for v11, but I incorrectly released 2.0.1 marked compatible with v10. (That's fixed for 2.0.2.) For v10 you want to be on Dungeon Draw 1.2.2.

**Comment by Hentik** [comment]
Thank you! It works again, i should have tried that before asking stupid questions. Again thanks!

**Comment by mcglincy** [comment]
It wasn't a stupid question at all, since it was me who broke things for v10 upgrades :) glad Dungeon Draw is working for you now, and let me know if you hit any other issues.
