### ISSUE TITLE
Trusted Players with journal permissions are unable to draw

### ISSUE THREAD

**Issue by themaster567** [mcglincy/dungeondraw-foundry-vtt#117]
Whenever my player tries to draw, he gets the error "lacks permission to update JournalEntry". I have tried fiddling with various settings to no avail.

**Comment by mcglincy** [comment]
Does the player have permission to the particular JournalEntry that Dungeon Draw created for this scene? (you can find it in the right nav Journal tab, in the Dungeon Draw folder... should have the same name as the scene)

**Comment by themaster567** [comment]
Thank you, that was it. Sorry for the wasted ticket!

**Comment by mcglincy** [comment]
Not a problem! Glad we got it working for you :)
