### ISSUE TITLE
Cannot draw anything 

### ISSUE THREAD

**Issue by krasnoludkolo** [mcglincy/dungeondraw-foundry-vtt#118]
Hello,
When I try to draw anything nothing happen. In console I get

```
Uncaught TypeError: Cannot destructure property 'preview' of 'e.interactionData' as it is undefined.
    at _c._onClickLeft (dungeonlayer.js:279:13)
    at Canvas._onClickLeft (foundry.js:24402:52)
    at MouseInteractionManager.callback (foundry.js:27872:45)
    at MouseInteractionManager._handleClickLeft (foundry.js:28069:10)
    at MouseInteractionManager._handleMouseDown (foundry.js:28049:22)
    at a.emit (index.js:181:35)
    at r.dispatchEvent (interaction.min.mjs:8:12235)
    at r.processPointerDown (interaction.min.mjs:8:14214)
    at t.recursiveFindHit (interaction.min.mjs:8:4098)
    at t.findHit (interaction.min.mjs:8:4157)
_onClickLeft @ dungeonlayer.js:279
_onClickLeft @ foundry.js:24402
callback @ foundry.js:27872
_handleClickLeft @ foundry.js:28069
_handleMouseDown @ foundry.js:28049
a.emit @ index.js:181
r.dispatchEvent @ interaction.min.mjs:8
r.processPointerDown @ interaction.min.mjs:8
t.recursiveFindHit @ interaction.min.mjs:8
t.findHit @ interaction.min.mjs:8
r.processInteractive @ interaction.min.mjs:8
r.onPointerDown @ interaction.min.mjs:8
```

**Comment by mcglincy** [comment]
If you're on v10, you may need to uninstall & reinstall. When getting the v11-compatible release of Dungeon Draw ready, I mistakenly listed a v11-only build as compatible with v10, which could cause the error you're seeing. (I've since removed that bad release.)

**Comment by krasnoludkolo** [comment]
hm, I just reinstall module and I still got same issue. I'm using v10.303

**Comment by pwim** [comment]
I also got this issue on 10.303, as I had installed 2.0.1. This was done via The Forge, which listed it as the most recent v10 compatible version. Since you mentioned you removed the bad release, maybe it is caching it there?

**Comment by aeciobf** [comment]
Same error here!

**Comment by mcglincy** [comment]
I'm just finishing up travel, will take a look at these errors this week (and ping Forge folks to find out how module caching/versioning works there). Sorry for the delay!

**Comment by grimmash** [comment]
Also unable to draw anything.  When left-clicking:
Uncaught TypeError: e.interactionData is undefined
    _onClickLeft dungeonlayer.js:279
    _onClickLeft foundry.js:24343
    callback foundry.js:27813
    _handleClickLeft foundry.js:28010
    _handleMouseDown foundry.js:27990
    emit index.js:181
    dispatchEvent interaction.min.mjs:8
    processPointerDown interaction.min.mjs:8
    recursiveFindHit interaction.min.mjs:8
    findHit interaction.min.mjs:8
    processInteractive interaction.min.mjs:8
    onPointerDown interaction.min.mjs:8
2 [dungeonlayer.js:279:52](https://assets.forge-vtt.com/bazaar/modules/dungeon-draw/2.0.1/src/dungeonlayer.js)
    _onClickLeft dungeonlayer.js:279
    _onClickLeft foundry.js:24343
    callback foundry.js:27813
    _handleClickLeft foundry.js:28010
    _handleMouseDown foundry.js:27990
    emit index.js:181
    dispatchEvent interaction.min.mjs:8
    processPointerDown interaction.min.mjs:8
    recursiveFindHit interaction.min.mjs:8
    findHit interaction.min.mjs:8
    processInteractive interaction.min.mjs:8
    onPointerDown interaction.min.mjs:8

**Comment by mcglincy** [comment]
I've removed any DD github releases that had the bad mix of v10-allowing manifest + v11-only code (which is what causes the "e.interactionData is undefined error".

Anyone still encountering issues may want to try uninstalling and then reinstalling by using a specific manifest URL:

DD v1.2.2, compatible with v10:
https://github.com/mcglincy/dungeondraw-foundry-vtt/releases/download/1.2.2/module.json

DD v2.1.0, compatible with v11:
https://github.com/mcglincy/dungeondraw-foundry-vtt/releases/download/2.1.0/module.json

**Comment by mcglincy** [comment]
I chatted with Forge support, and the Bazaar is still showing broken 2.0.0 / 2.0.1 as installable versions. They are going to remove those listings.

**Comment by mcglincy** [comment]
From KaKaRoTo: 2.0.1  was marked as compatible with v10, so those on v10 would have been on 2.0.1 and that would have seemed like the latest version.. with it now removed, they'd get prompted to downgrade instead 👍 

Going to mark this as closed; if people are still hitting problems please re-open this issue and/or ping me. Thanks!
