### ISSUE TITLE
Problem with doors on V12.

### ISSUE THREAD

**Issue by michalzc** [mcglincy/dungeondraw-foundry-vtt#134]
Foundry: V12.328
Dungeon Draw: 3.0.2
Platform: Chromium and Electron App on Linux

Doors are not aligned with walls and don't make "holes" when drawn on walls. Tested with different systems on a fresh world without any other modules enabled. Please have a look at the attached screencast.
[vokoscreenNG-2024-07-12_11-08-18.webm](https://github.com/user-attachments/assets/e516336e-51cb-40f4-be8e-336f3be88f65)

**Comment by danieldsj** [comment]
Observing the same symptoms.

Foundry Stable 12 Build 331 is the server. 
Firefox 128.3.1esr 64-bit is the client.

**Comment by PXR5** [comment]
I am also seeing this behaviour since V12 as are others in the OSE/UFT Discord. Everything worked perfectly on V11.
Version 12 Stable, 12.331, Brave [Version 1.71.118 Chromium: 130.0.6723.70 (Official Build) (arm64)]

**Comment by mcglincy** [comment]
Sorry, day job has given me very few Foundry cycles recently.

I started debugging this tonight and have a hypothesis, which is that v12 somehow broke snap in Dungeon Draw... which means doors aren't snapping exactly to a given wall's x or y position, which means the code doesn't see the wall/door as overlapping and thus won't split the wall.

**Comment by mcglincy** [comment]
Just released 3.0.3 with snap fixed (at least for my local testing). This also fixed the doors-not-splitting-walls problem, as now doors are snapped, which lets them line up exactly with the wall and get detected as overlapping.

Please re-open if this doesn't fix it for you.

**Comment by danieldsj** [comment]
> Just released 3.0.3 with snap fixed (at least for my local testing). This also fixed the doors-not-splitting-walls problem, as now doors are snapped, which lets them line up exactly with the wall and get detected as overlapping.
> 
> Please re-open if this doesn't fix it for you.

Just tested it.  The doors are aligned with the walls, however the sections of walls that should be "cut and deleted" or spliced out are still there.

**Comment by danieldsj** [comment]
I cannot see the option to reopen a closed issue.

**Comment by PXR5** [comment]
I am also seeing walls overlapping doors even using DD 3.0.3. (I will make a new 'ping' incident referring to this since we apparently do not have permission to re-open this case)

<img width="1248" alt="Screenshot 2024-11-06 at 10 14 20" src="https://github.com/user-attachments/assets/27061290-2a82-4dd4-aa4e-14d61e997127">

**Comment by mcglincy** [comment]
Reopened, and thanks for testing! I'll do some more debugging and fix.

**Comment by mcglincy** [comment]
Apparently I built 3.0.3 without the updated code :P

I've build 3.0.4 that should now include the snap fix. Can someone besides me test and confirm happiness?

**Comment by PXR5** [comment]
Just made a quick test using 3.0.4 and it looks good to me. 😁

<img width="465" alt="Screenshot 2024-11-06 at 22 58 22" src="https://github.com/user-attachments/assets/d18dda73-3bd9-4d4f-9f3d-d0ad03b3b314">

**Comment by Xaeroxe** [comment]
This worked for my game, thanks!

**Comment by mcglincy** [comment]
Marking fixed.
