### ISSUE TITLE
Snap-to-grid only affects rectangle's end point, not its start point

### ISSUE THREAD

**Issue by manabreak** [mcglincy/dungeondraw-foundry-vtt#136]
If you draw multiple rectangles and try to aim them to start from a grid point and make them also end at a grid point, the starting point is always off a little bit.

![Kuvakaappaus_2024-07-21_06-40-24](https://github.com/user-attachments/assets/9d91fd63-797d-4de7-86ef-8c1356bd1c47)

In the screenshot, both rectangles are drawn starting from the top-left grid point and ending at the bottom-right grid point. Notice how the start point (i.e. the left and top edges) are not aligned with the grid, whereas the end point (the right and bottom edges) are aligned correctly.

**Comment by mcglincy** [comment]
Just released 3.0.3 with snap fixed (at least for my local testing).

Please re-open if this doesn't fix it for you.
