### ISSUE TITLE
Doors do not snap to grid, creating leaky lighting

### ISSUE THREAD

**Issue by manabreak** [mcglincy/dungeondraw-foundry-vtt#137]
![Kuvakaappaus_2024-07-21_07-19-07](https://github.com/user-attachments/assets/6abcf721-3b4c-4989-89fe-76cfba5754ef)

**Comment by mcglincy** [comment]
Just released 3.0.3 with snap fixed (at least for my local testing).

Please re-open if this doesn't fix it for you.
