### ISSUE TITLE
Non-GM Permissions

### ISSUE THREAD

**Issue by tuirgin** [mcglincy/dungeondraw-foundry-vtt#18]
It would be nice to allow Trusted Players to be able to use the tool. In old school D&D, the players will draw maps based on GM description. Currently I have to make the mapper an assistant GM, which also means that they're going to receive all Blind and GM rolls, which are used for various skill checks. For example, in Old-School Essentials attempts to hide in shadows, or detect treasure traps are configured as blind rolls saving the GM from having to roll for the player. 

We'll work around these blind & gm rolls for now—the functionality is too nice to skip!

**Comment by mcglincy** [comment]
Yeah, totally agree. The GM/assistant GM permissions are currently needed to allow deletion and re-creation of the automatic lighting walls and doors, but as you point out it allows a lot of other permissions and visibility, too. 

I'll take a look to see if there's a way a Trusted Player could be allowed to do the wall delete/create.

**Comment by tuirgin** [comment]
For my use particular use-case, the walls/lighting/doors aren't important at all, but I really do understand that my use case isn't common—even a lot of old school groups don't do player mapping, especially with online play.

Thanks for looking at this!

**Comment by mcglincy** [comment]
I think I found a workable permissions compromise: I can make the dungeon draw tools show up for trusted players, and the map-drawing mostly works. 

A few wrinkles:
- GM / assistant permissions are needed to delete and create walls, as well as to edit the current scene (e.g., when applying themes that twiddle the scene background color or grid). For Trusted Player, I can simply skip doing these operations.
- Each scene's dungeon is saved in a JournalEntry. Trusted Player can create new JournalEntries (yay), but if you first start the dungeon map as GM you will need to manually edit permissions to allow Trusted Player to edit the GM-created JournalEntry (boo). Same issue if you want two Trusted Players to be able to both edit the same dungeon map / JournalEntry.

Does this sound sufficient for how you'd like Trusted Player to make maps?

**Comment by tuirgin** [comment]
That sounds close to perfect. The permissions twiddling is unlikely to be more than once per session, and usually less—all players are trusted, but it's usually the same person who does mapping each session. And the themes are unlikely to be used until after the map is complete, anyway.

Thanks so much for looking into this.

**Comment by mcglincy** [comment]
Fixed in 0.8.0. Let me know how this works for you!

**Comment by tuirgin** [comment]
Terrific! I'll test it out in the next day or two and let you know either way. Thanks so much.

**Comment by tuirgin** [comment]
> Fixed in 0.8.0. Let me know how this works for you!

This does exactly what I needed. I did notice one odd behavior, but I'll put that in a new issue, as it doesn't seem to be related to permissions.
