### ISSUE TITLE
Drawing "over grid and tokens"

### ISSUE THREAD

**Issue by uLotUu** [mcglincy/dungeondraw-foundry-vtt#2]
For some reason whenever I try to draw the dungeon it always draws over my grid and tokens.

**Comment by mcglincy** [comment]
Thanks for the bug report. 

My guess is Dungeon Draw is not playing nice with some other module. Could you send me a list (or screenshot) of what other modules you have enabled? And then, try disabling everything except Dungeon Draw, and see if it's still working incorrectly.

**Comment by mcglincy** [comment]
I just got a report from another user that the Perfect Vision module may be causing Dungeon Draw to act badly. I'll do some testing and debugging.

**Comment by mcglincy** [comment]
I spoke with the Perfect Vision module author, and they've added compatibility code to the latest version of Perfect Vision (2.10.8).

https://github.com/dev7355608/perfect-vision/issues/147
