### ISSUE TITLE
New interior walls overlapping previously made doors.

### ISSUE THREAD

**Issue by pseudocode** [mcglincy/dungeondraw-foundry-vtt#32]
**Scenario**:
- Draw a rectangular room with add tool.
- Draw a door in the middle of the south wall.
- "You're in a 15x10 room, mildew emanates from the wet dungeon wall. There's an ogre noise coming from a door in the south".
- Players gear up, want to open south door.
- Draw another rectangular room to the south, interior wall dividing both.
- Player opens door. 

**Result**: Can't see through, can't walk through, as the interior wall spans the whole width of the room, instead of three 5' segents wall-door-wall. 

![overlapping_wall](https://user-images.githubusercontent.com/119981/143273254-a716362e-5036-4d59-873f-44118cb0f054.jpg)

Re-drawing the door as a workaround makes it look better in DungeonDraw (i.e. no line through the middle of the door), but opening the door has the same results, as the previous door is still underneath, not accessible.

(Stil, congrats on the new release, lots of awesome features. Love the pace!)

**Comment by mcglincy** [comment]
Thanks for the bug report!

I added doors breaking up a wall when you draw a door on top of an interior wall, but it looks like I also need to break up a wall when one gets drawn on top of an existing door. I'll think about how best to do that.

**Comment by mcglincy** [comment]
I think I've got a workable implementation of this. I'm going to test a bit more, then will ship it in the next 0.10.0 release either later today or tomorrow.
