### ISSUE TITLE
Introduce invisible walls

### ISSUE THREAD

**Issue by Lim-Dul** [mcglincy/dungeondraw-foundry-vtt#34]
This is a feature request:
Allow the placing of invisible walls that could be used for windows, jail cells etc. - so walls blocking movement but not sight.

Possible visual representation:
Dotted or dashed line

**Comment by pbtura** [comment]
I took a stab at implementing this (see: https://github.com/mcglincy/dungeondraw-foundry-vtt/pull/101). The basic functionality is there, but I haven't been able to figure out how to get the added walls to render in the Dungeon Draw view.

**Comment by mcglincy** [comment]
Implemented in #101.
