### ISSUE TITLE
Secret Doors

### ISSUE THREAD

**Issue by CarWashMeNot** [mcglincy/dungeondraw-foundry-vtt#35]
Is there any way to add secret doors? I tried with the tools from foundry, but that does not seem to work..

**Comment by mcglincy** [comment]
Right now there isn't, beyond manually modifying the walls and doors yourself (and then not modifying the dungeon any more, since it will regenerate walls and doors). 

But, if this is something you think would be useful, I can add it to the TODO list. There's a similar open request for the ability to draw a dotted-line wall that would block movement but not sight.

**Comment by CarWashMeNot** [comment]
>  if this is something you think would be useful, I can add it to the TODO list.

That would be awesome!

**Comment by eivindhusby** [comment]
Being able to set the door default to secret would be fantastic. I use Foundry to play IRL, and I don't like having the door icons visible on the map. Especially since they show through the FoW I use. Secret doors solves this problem.

**Comment by mcglincy** [comment]
Cool. I'll plan to work on this feature next. Maybe a new tool button ("Add Secret Door"), and it's visible as a normal wall for players, and as a wall with an S through it for GMs? Sort of like:

![Screen Shot 2021-11-30 at 8 04 58 AM](https://user-images.githubusercontent.com/189172/144061681-34d66e63-77e4-47a3-a754-781fa723c79f.png)

**Comment by eivindhusby** [comment]
Awesome. I realize that I might be a very special edge case, but for my use, I want it to look like a normal door as a map visual, but be registered as a secret door in the Foundry wall settings, as I just don't want the extra icon that Foundry shows for doors.
If the settings would let me choose the combination of Foundry door/Dungeon Draw door, that would be perfect.
I don't have the slightest clue about how much that complicates programming though :p

**Comment by mcglincy** [comment]
Ok, so maybe two config settings for a secret door: how it appears to GMs and how it appears to players... and you could choose between s-secret door, normal-looking door, or blank wall for each. And then for the auto-generated Foundry lighting wall, Is Door? will be set to "Secret" for all cases.

**Comment by eivindhusby** [comment]
Sounds perfect for my needs at least :D
The biggest issue for me, with the current setup, is that if I change anything at all, every door is reset to a normal door.
And thank you for being so responsive here. The speed of development for this module has been quite impressive.

**Comment by mcglincy** [comment]
Implemented in upcoming 0.12.0.

![Screen Shot 2021-11-30 at 4 15 06 PM](https://user-images.githubusercontent.com/189172/144136808-03237897-a0bc-47dc-9136-48b5c38febf9.png)

![Screen Shot 2021-11-30 at 4 12 21 PM](https://user-images.githubusercontent.com/189172/144136473-18de19e5-bcb0-4585-bae0-10a0e4d04e08.png

![Screen Shot 2021-11-30 at 4 14 08 PM](https://user-images.githubusercontent.com/189172/144136662-12150a30-8a27-4454-9df4-a3d1b2610c6e.png)
)

**Comment by CarWashMeNot** [comment]
Uuuuh it's working great! Thank you very much! :)
