### ISSUE TITLE
[Bug] Dungeon Draw don't Work in same Worlds 

### ISSUE THREAD

**Issue by brunocalado** [mcglincy/dungeondraw-foundry-vtt#48]
Hi. Great module!

I'm having a weird bug. I can't use dungeondraw in some worlds. If I create a new world I can use it normally.

I already tried to find errors in the console, there is none.

I used Find the Culprit and disable everything, but this don't make the problem go away.
https://user-images.githubusercontent.com/4999783/145676192-05fac258-7d57-4948-9482-5e6df7f3d825.mp4
![image](https://user-images.githubusercontent.com/4999783/145676266-61cb95cb-65a0-4955-b26a-af45bd70cacb.png)

google chrome
Local host
foundry 8.9
dungeondraw 13

**Comment by brunocalado** [comment]
I just have to remove the background image...

**Comment by mcglincy** [comment]
Nice, glad you figured it out!

And as you've discovered, Dungeon Draw currently isn't compatible with a background image set in the scene (which covers up the dungeon map). I did add a background image setting in the Dungeon Draw config, though, so you can accomplish the same visual effect... you just have to set the background image on Dungeon Draw and not the scene.

Currently Foundry uses the "background" layer for both the scene background image as well as background placeable tiles. I wanted the Dungeon Draw map to be below placeable tiles, so users could place tiles for furniture, objects, etc... but that also means Dungeon Draw's layer is also below the scene background image :P

I'll update the Dungeon Draw README and Foundry page to let users know about this gotcha.
