### ISSUE TITLE
Revealing map when adding new drawings 

### ISSUE THREAD

**Issue by Kreals** [mcglincy/dungeondraw-foundry-vtt#53]
Game System: DnD5e
Modules: only Dungeon Draw 

**Issue**
When drawing new dungeon pieces, players will occasionally see the dungeon as if no walls were in place, revealing the map up to their controlled tokens vision. There is also a similar issue with new drawings revealing rooms adjacent to a room that the controlled token is in. This can be problematic when trying to secretly draw dungeons on the fly.

**Steps to recreate** 
1. create new world and enable Dungeon Draw
2. create scene and set darkness to 1
3. draw a rectangular piece of dungeon
4. create a player account and log in through browser
5. create a token inside the rectangular dungeon piece and set dim vision to 60, bright vision to 30 and then assign to player
6. draw unconnected dungeon pieces on the canvas

PS. Really like the idea of this module.

**Comment by mcglincy** [comment]
Thanks for the bug report! My guess is this might be happening because Dungeon Draw deletes all existing walls it made before making new ones... so it may be possible for players to get a glimpse of "no walls" before the new walls are re-made. I'll see if I can combine the wall delete + remake into a single database change.

**Comment by Kreals** [comment]
yeah i got the feeling that it may be due to processing time between deletion and creation. Quick fix might be to create first then delete, would probably still have visual artifacts but they _should_ be confined to already visible areas.

**Comment by mcglincy** [comment]
Fixed in 0.16.2. Changed wall creation to create new walls as one update, before deleting old walls as a second update.
