### ISSUE TITLE
Version number and manifest pointer mismatch.

### ISSUE THREAD

**Issue by Kreals** [mcglincy/dungeondraw-foundry-vtt#54]
When trying to install through foundry the version number is quoted as '0.15.1' and that is where the manifest file link points to, but it fails to install. I notice the version release on github is 0.15.0 so i changed the manifest link to point there which allowed me to install.

**Comment by mcglincy** [comment]
Thanks for notifying me - apparently I forgot to actually release 0.15.1 :P
Done.

**Comment by Kreals** [comment]
glad i could help.
