### ISSUE TITLE
Allow different floor textures on different parts of the map

### ISSUE THREAD

**Issue by mcglincy** [mcglincy/dungeondraw-foundry-vtt#7]
This one may be hard, as we don't currently keep track of separate sections of map geometry. Maybe this could be a "floor tiling" tool, with a chosen texture when painting?

**Comment by altair984** [comment]
i think to pain a different texture for parts of the maps is so necesary because u can have middle of dungeon in rock and another part in paviment floor

**Comment by mcglincy** [comment]
Implemented as "theme painter / eraser" tools in upcoming 0.11.0.
