### ISSUE TITLE
Restrict players from seeing dungeon draw in the tool bar

### ISSUE THREAD

**Issue by Kreals** [mcglincy/dungeondraw-foundry-vtt#75]
Currently players can access all the dungeon draw tools, some work some don't. This could very easily become problematic. I suggest hiding it from players or have it as an option that is off by default.

**Comment by mcglincy** [comment]
Thanks for the bug report!

The Dungeon Draw tools should only be visible to user roles GM, Assistant GM, and Trusted Player... and all visible tools should work. I'll run through the roles/tools and see if I borked something.

**Comment by Kreals** [comment]
I see, no the players are trusted players so it's working as you intended.  My concern is it is quite a powerfull tool that could really mess up a scene, so some options for permission settings would be helpful.

Would be nice if we could toggle it independently in the user management settings or maybe just a toggle box in the module settings menu to turn it off for all players. I guess this is more of a feature request and not super urgent or anything.

**Comment by yjeroen** [comment]
I think as well that Trusted Players should not be able to use Dungeon Draw. That's for Assistant GM's.

**Comment by mcglincy** [comment]
Dungeon Draw + Trusted Players permission is intended to allow someone to run a game where the players do the mapping themselves... but I totally get that that could be a bad fit in other games. I'll look at adding a custom permission, and if that's not simple to accomplish in Foundry I'll add a new module setting ("Allow Trusted Players" or similar).

**Comment by Kreals** [comment]
Yeah, i can see both use cases. Thanks for considering this one.

**Comment by mcglincy** [comment]
Added a "Allow Trusted Players" checkbox to module settings. Fixed in 0.18.0.
