### ISSUE TITLE
Add Japanese translations for new localizations

### ISSUE THREAD

**Issue by mcglincy** [mcglincy/dungeondraw-foundry-vtt#79]
I localized the text descriptions of the settings, but unfortunately I don't know Japanese :) 

@BrotherSharper - could I get your help translating these to Japanese? Thanks!

  "DD.SettingAllowTrustedPlayers": "Allow Trusted Players",
  "DD.SettingSnapToGrid": "Snap to grid",
  "DD.SettingSupport3DCanvas": "Enable support for 3D Canvas module",

**Comment by BrotherSharper** [comment]
@mcglincy Of course! Here you go!

```
"DD.SettingAllowTrustedPlayers": "優良プレイヤー許可",
"DD.SettingSnapToGrid": "マス目に合わせる",
"DD.SettingSupport3DCanvas": "3D化（3D Canvas）サポートを有効化",
```

Thank you for letting me know of new strings and thank you for adding them to the localization file. It saves me a lot of time (as I have 100+ repositories I need to keep watch)

**Comment by mcglincy** [comment]
Awesome, thank you @BrotherSharper ! I've updated ja.json accordingly.
