### ISSUE TITLE
Decluttering the Buttons

### ISSUE THREAD

**Issue by Bolt7** [mcglincy/dungeondraw-foundry-vtt#83]
I love this module, but there are approximate too many buttons in the tab. A few ways to reduce that:

- [ ]  Add keybinds for undo and redo (ideally that default to ctrl-z and ctrl-y respectively), and a setting to remove the buttons.
- [ ]  Add an addition/subraction toggle and remove the 3 different subracting tools (or have a setting to change the layout to that). A keybind for the toggle would be nice as well.

That'd go from 16 to 12 buttons (one of them being a toggle), increase usage speed (keybinds are faster than buttons imo), and also enable subtraction of a polygon or freehand shape to the map.

**Comment by mcglincy** [comment]
Agree the button strip is getting a bit crowded, and thanks for the suggestions! I'll take a look.

**Comment by mcglincy** [comment]
Sorry, got buried under some other projects. 

I've added ctrl-z/ctrl-y keybindings in the latest 0.20.0 release. 

Reorganizing the buttons is trickier, as it will need a custom control widget / UI. Foundry's default control buttons is just a single vertical list of either a "button" or a tool-wide toggle... meaning it can't handle an add/sub toggle + tool select toggle at the same time. I'm playing around with a new button widget that can handle the more complicated toggles and layout.

**Comment by mcglincy** [comment]
Current button reorg. Doing more testing before releasing.

<img width="329" alt="Screen Shot 2022-04-18 at 7 47 54 AM" src="https://user-images.githubusercontent.com/189172/163803947-0e60bedb-d52d-4b8b-8e86-f2e5285e7569.png">

**Comment by mcglincy** [comment]
Shipped in new DD version 0.22.0.
