### ISSUE TITLE
Outside Buildings

### ISSUE THREAD

**Issue by Cosmic-Lattee** [mcglincy/dungeondraw-foundry-vtt#84]
Just wanted to say this module is amazing, and thank you for it!

So something that could be neat is using Dungeon Draw to create scenes like this:

![image](https://user-images.githubusercontent.com/24766235/150084261-16eb8d9a-2053-4ac5-962d-302050422b0c.png)

This is a city street map that I made.

While obviously this works currently those doors don't function because the lines aren't deleted like they are for interior walls. So I would have to go in and manually move them. Sort of a niche thing and I understand if it ultimately is outside of the scope for this module.

Just thought I would offer it as a suggestion.

Thanks!

**Comment by ian612** [comment]
I would also love something like this added. To be able to use the door tool to make doors and the invisible wall tool to make windows that face outside would be awesome

**Comment by mcglincy** [comment]
I'll take a look! 

Right now Dungeon Draw keeps track of a total dungeon "geometry" as you add/remove shapes to the dungeon, and then creates Foundry walls for the perimeter of that geometry. I think for this to work for "outdoors", DD would need to split the perimeter walls around any doors or invisible walls.

**Comment by mcglincy** [comment]
Implemented in upcoming 1.1.0. I'll ship that release, then let @Cosmic-Lattee and @ian612 confirm it's working for them before I close this issue.

**Comment by ian612** [comment]
Awesome, thank you!

**Comment by ian612** [comment]
It doesn't seem to be working for me on my world where I use Dungeondraft. Doors are still working okay in 1.1.0, but exterior windows don't seem to be wrapped around. Will try it out on a brand new world to see if it works there.

**Comment by ian612** [comment]
This is on a brand new world, the first image is a room with a door and window (invisible wall) from the GM view. Second is the same thing from a player view. Third is the view with the walls visible, you can see the invisible wall didn't split the normal walls like the door did.

![image](https://user-images.githubusercontent.com/34078802/200400441-def9da01-df32-4ab3-9a84-61283f4ef2dd.png)
![image](https://user-images.githubusercontent.com/34078802/200400469-b79f1c84-6343-431d-950a-1fb12dc34350.png)
![image](https://user-images.githubusercontent.com/34078802/200400698-153daa35-5e11-4ffd-a4d9-127cf3a2a3b6.png)

**Comment by mcglincy** [comment]
Weird, the 1.1.0 build wasn't including the latest-greatest code. I've built a new 1.1.1 that should. Do you mind updating and re-trying? Thanks!

**Comment by mcglincy** [comment]
Awesome! Marking this issue closed.
