### ISSUE TITLE
DungeonDraw causes Foundry canvas failure after custom textures are moved in file system

### ISSUE THREAD

**Issue by epsilon7430** [mcglincy/dungeondraw-foundry-vtt#89]
Using custom texture graphics (background and floor) for a scene using DungeonDraw.  Outside of Foundry, I reorganized the graphics in a different folder.  Activating that scene then threw file not found console errors.  Worse, the Foundry client does not recover from this - the canvas fails to load for all scenes and requires browser refresh to resolve (and requires the default active scene to not be the one that caused the issue otherwise it fails on reload).  Using DungeonDraw config to reset the file paths solves the issue.

It would be helpful if DungeonDraw could fail more elegantly in cases when graphics are not found.  Thanks

Win 10; Foundry 9.266

**Comment by mcglincy** [comment]
Agree, missing textures should be handled more gracefully. I'll take a look!

**Comment by mcglincy** [comment]
Screencap of console errors from missing background img and floor texture:

![Screen Shot 2022-04-12 at 12 13 54 PM](https://user-images.githubusercontent.com/189172/163017601-988c36e8-3577-42ac-bfc8-254dc7618996.png)

**Comment by mcglincy** [comment]
Fixed in new version DD 0.21.1. Missing texture no longer muck the canvas, and will show a UI notification indicating the texture file(s) that failed to load.
