### ISSUE TITLE
FEATURE REQUEST: Animated Image Support

### ISSUE THREAD

**Issue by Zephyr2011** [mcglincy/dungeondraw-foundry-vtt#91]
**DESCRIPTION:** Allow themes to specify webm files for textures and play the corresponding animation. This would ideally also apply to saving a Dungeon Draw output to the scene background.

**CURRENT FUNCTIONALITY:** Currently, themes can specify webm files for textures, but they are "paused" forever, there is no way to "play" the animation.

**USE CASES:** Ideal for effect heavy dungeons such as lava or water without the need for additional lights, tiles, or macros.

**ADDITIONAL NOTES/INFO:** Not sure how feasible this is, but it would be helpful. Foundry drawings cannot specify webm files, but scene backgrounds can be set to webm. Scene backgrounds set to webm will play forever with no way to pause or restart the animation.

**Comment by mcglincy** [comment]
I remember this working at one point; I'll test and report back.

**Comment by mcglincy** [comment]
Confirmed webm isn't animated. Will debug and fix.

**Comment by mcglincy** [comment]
Fixed in 0.23.0.
